# Generated by Django 6.0.5 on 2026-06-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_deliverypartner_order_delivered_at_order_shipped_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_partner',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipped_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_id',
        ),
        migrations.DeleteModel(
            name='DeliveryPartner',
        ),
    ]
