# Generated by Django 6.0.5 on 2026-06-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_partner',
            field=models.CharField(blank=True, choices=[('delhivery', 'Delhivery'), ('bluedart', 'Blue Dart'), ('dtdc', 'DTDC'), ('ekart', 'Ekart Logistics'), ('xpressbees', 'XpressBees'), ('shadowfax', 'Shadowfax'), ('ecom', 'Ecom Express'), ('amazon', 'Amazon Logistics'), ('shiprocket', 'Shiprocket'), ('other', 'Other')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, help_text="CTA button label e.g. 'Shop Now'", max_length=40),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_url',
            field=models.CharField(blank=True, help_text='Relative or absolute URL e.g. /shop/?sale=1', max_length=200),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.CharField(blank=True, help_text='Short supporting description (max 180 chars)', max_length=180),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number = shown first'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='tag_text',
            field=models.CharField(blank=True, help_text="Small pill label above heading e.g. '✦ New Arrivals'", max_length=60),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage (%)'), ('flat', 'Flat (₹)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Cash On Delivery'), ('razorpay', 'Razorpay'), ('online', 'Online Payment')], default='cod', max_length=50),
        ),
    ]
