# Generated by Django 6.0.5 on 2026-06-08 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_enabled', models.BooleanField(default=False, help_text='Allow Cash on Delivery for new orders.')),
                ('order_modification_enabled', models.BooleanField(default=False, help_text='Allow admin to send order-modification proposals to customers.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
        migrations.CreateModel(
            name='OrderModificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_changes', models.TextField(help_text='Human-readable description of what will change in the order.')),
                ('admin_note', models.TextField(blank=True, help_text='Message shown to the customer in the email.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('token', models.CharField(blank=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_requests', to='web.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
