# Generated by Django 6.0.5 on 2026-06-09 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_storesettings_ordermodificationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('lt1', 'Less than 1 year'), ('1yr', '1 year'), ('2yr', '2 years'), ('3yr', '3 years'), ('4yr', '4 years'), ('5yr', '5 years'), ('6yr', '6 years'), ('7yr', '7 years'), ('8yr', '8 years'), ('9yr', '9 years'), ('10yr', '10 years'), ('custom', 'Custom')], max_length=20)),
                ('custom_label', models.CharField(blank=True, help_text="Only used when label = 'custom'", max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='web.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
