# Generated by Django 6.0.5 on 2026-06-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_productvariant_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='label',
            field=models.CharField(choices=[('lt1', 'Less than 1 year'), ('1yr', '1 year'), ('2yr', '2 years'), ('3yr', '3 years'), ('custom', 'Custom')], max_length=20),
        ),
    ]
