# Generated by Django 6.0.5 on 2026-06-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_productvariant_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
